# Generated by Django 3.2 on 2022-04-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarattendees',
            name='seminar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminarattendees',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Attendees Name'),
        ),
    ]
