# Generated by Django 3.2 on 2022-04-24 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('registration_no', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True, verbose_name='Contact Number')),
                ('image', models.ImageField(upload_to='ngo\\banner')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NgoBankDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account_no', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name="Account Holder's Name")),
                ('bank_name', models.CharField(max_length=255)),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ngo.ngo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundRaise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('patient_name', models.CharField(max_length=255, verbose_name='Patient Name')),
                ('prescription', models.ImageField(default='default.jpg', upload_to='ngo\\patient\\prescription')),
                ('patient_address', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.ngo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='Anonymous User', max_length=255, verbose_name="Donar's Name")),
                ('address', models.TextField()),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IN', unique=True, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.ngo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
