# Generated by Django 3.2 on 2022-04-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraise',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='fundraise',
            name='is_raised',
            field=models.BooleanField(default=False, verbose_name='Raised Completed'),
        ),
    ]
