# Generated by Django 3.2 on 2022-04-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0002_auto_20220430_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraise',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
