# Generated by Django 3.2 on 2022-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cremation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cremation',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cremation',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
