
class Contants:
    ROLE_ADMIN='ADMIN'
    ROLE_HOSPITAL_ADMIN='HOSPITAL'
    ROLE_USER='USER'
    RELIGION_HINDU="HINDU"
    RELIGION_CHRISTIAN="CHRISTIAN"
    RELIGION_MUSLIM="MUSLIM"
    RELIGION_SIKH="SIKH"
    PRIEST='PRIEST'
    VEHICLE='VEHICLE'